global:
  scrape_interval: 1s  # How frequently to scrape metrics from targets

scrape_configs:
  - job_name: 'scale_sync_app'  # A job name for the app
    static_configs:
      - targets: ['localhost:8080']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: postgresql-exporter'
    static_configs:
      - targets: ["postgresql-exporter:9187"]
  - job_name: postgresql'
    static_configs:
      - targets: ["postgresql:5432"]
